### ISSUE TITLE
Failing without reboot on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by groggemans** [geerlingguy/ansible-role-firewall#17]
```
TASK [geerlingguy.firewall : Ensure the firewall is enabled and will start on boot.] ***
fatal: [ansible-dev-ubuntu]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'firewall'\": "}
```

It runs fine after a reboot.

**Comment by groggemans** [comment]
Also happens on newer Debian hosts.

Reason: the new service file is not detected (ansible/ansible-modules-core#191)
Should be fixed in ansible v2.2 (ansible/ansible#3660) but will require the systemd module to be used.

Maybe you could add the `systemctl daemon-reload` command to the role for older ansible versions.

**Comment by geerlingguy** [comment]
Wrong repo in above link :) — https://github.com/ansible/ansible-modules-core/pull/3660

**Comment by geerlingguy** [comment]
I'm seeing issues like this pop up for many of my roles now, including:
- MySQL: https://github.com/geerlingguy/ansible-role-mysql/issues/128 (sort-of-related)
- Solr: https://github.com/geerlingguy/ansible-role-solr/issues/33 (sort-of-related)
- Firewall: this issue...

Just documenting here for my own sanity.

**Comment by kathgironpe** [comment]
Doesn't work with Debian either.

**Comment by geerlingguy** [comment]
Note that the automated build (runs on CentOS 6, CentOS 7, Ubuntu 12, Ubuntu 14, Ubuntu 16, and Debian 8 at this time) _is_ passing with the latest code: https://travis-ci.org/geerlingguy/ansible-role-firewall

But there are some cases where it might not work, and it looks like Ansible 2.2 might have the fix (ref: https://github.com/geerlingguy/ansible-role-mysql/issues/128), so rather than try to figure out a hacky workaround, I'm going to wait for that and then see if it fixes those issues.

Also, in some cases, if you're working from a Windows workstation, check to make sure your line endings for the files in this role are set to 'Unix' and not Windows. That's caused some consternation for people deploying VMs in Windows via Vagrant using this role and the Ansible provisioner.

**Comment by kathgironpe** [comment]
@geerlingguy I am sorry. You are right. It works! Thank you for this.

**Comment by kathgironpe** [comment]
On my part, I forgot to reference the path for variables.

**Comment by geerlingguy** [comment]
@katgironpe Great, glad I could help!

@groggemans - I'm going to close this out, but please let me know if it's still an issue.

**Comment by groggemans** [comment]
Ok, Thanks!

**Comment by geerlingguy** [comment]
Reopening due to #958. Might add a switch for systemd systems and use it for Ubuntu 16.04, CentOS 7, Debian 8, etc. so they get the proper templated file.

**Comment by geerlingguy** [comment]
I have a fix, will push up a branch soon!

**Comment by kathgironpe** [comment]
@geerlingguy thank you!

**Comment by geerlingguy** [comment]
Still not using the unit file on CentOS 7. Will fix that now. See also: https://github.com/geerlingguy/ansible-role-mailhog/issues/15
