### ISSUE TITLE
Host loses connectivity after flushing iptables

### ISSUE THREAD

**Issue by seanf** [geerlingguy/ansible-role-firewall#2]
Controlling an Ubuntu 14.04 box, all connectivity was lost after the step which flushed iptables.   The firewall had previously been configured through UFW.  Perhaps the default rule was DROP rather than ACCEPT?

```
$ ansible-playbook -v zanata-wildfly.yml -i inventory

PLAY [zanata] ***************************************************************** 

GATHERING FACTS ***************************************************************
ok: [xx.xx.xx.xx]

TASK: [geerlingguy.firewall | Ensure iptables is installed (RedHat).] *********
skipping: [xx.xx.xx.xx]

TASK: [geerlingguy.firewall | Ensure iptables is installed (Debian).] *********
ok: [xx.xx.xx.xx] => {"changed": false}

TASK: [geerlingguy.firewall | Flush iptables the first time playbook runs.] ***
changed: [xx.xx.xx.xx] => {"changed": true, "cmd": ["iptables", "-F"], "delta": "0:00:00.002802", "end": "2014-08-21 03:11:54.650421", "rc": 0, "start": "2014-08-21 03:11:54.647619", "stderr": "", "stdout": ""}

TASK: [geerlingguy.firewall | Copy firewall script into place.] ***************
fatal: [xx.xx.xx.xx] => {'msg': 'FAILED: timed out', 'failed': True}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/sflaniga/zanata-wildfly.retry

xx.xx.xx.xx             : ok=3    changed=1    unreachable=1    failed=0

sflaniga:ansible (master*) $ cat zanata-wildfly.yml

---
- hosts: zanata
  sudo: yes
#  accelerate: true
  vars_files:
    - vars/main.yml
  roles:
    - { role: geerlingguy.firewall }
  tasks:

  - name: Add group "wildfly"
    group: name=wildfly

  - name: Add user "wildfly"
    user: name=wildfly group=wildfly home=/home/wildfly

  - name: Change ownership of WildFly directories
    file: path=/opt/wildfly owner=wildfly group=wildfly state=directory recurse=yes

sflaniga:ansible (master*) $ cat vars/main.yml
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
  - "5099" # for Ansible accelerated mode
  - "8080"

firewall_forwarded_tcp_ports:
  - { src: "80", dest: "8080" }

# firewall_forwarded_udp_ports: []


# firewall_additional_rules: []%
sflaniga:ansible (master*) $
```

**Comment by geerlingguy** [comment]
This role is intended to be used in lieu of `ufw`, and although you may be able to get ufw and iptables + this role working together correctly, I would rather not try to support the mix... Since iptables works on all the linux environments I work with, I try to continue using it for everything rather than ufw where it's available.

My guess is that what happened here was ufw was redirecting a port, or accepting connections, then when this role runs the first time, and drops those rules, the connection is no longer available.

**Comment by geerlingguy** [comment]
Please feel free to reopen if I'm missing what's going on here... one other note is that I haven't fully tested the role with 14.04 (only 12.04), so maybe there's something different about 14.04 causing an issue.

**Comment by seanf** [comment]
(I don't think I can re-open the issue.)

I don't normally use Ubuntu, but I have a feeling `ufw` might have been on by default (in 14.04).  

Perhaps to make the firewall role more robust, to avoid conflicts, it could disable `ufw` and ensure that the default rules are ACCEPT before flushing iptables.  Losing connectivity is never fun.

**Comment by geerlingguy** [comment]
I'll reopen this issue, then—I definitely need to do some more investigation on 14.04, especially since some of the network stack has change quite a bit!

**Comment by geerlingguy** [comment]
I've been testing this role on a few different clean installs of Ubuntu 14.04 minimal, and can't replicate the failure here; I wonder if the distribution you were using had a specific firewall rule in place that was redirecting a particular port or something for SSH, and flushing the rules cleared out that special firewall rule.

Can you try running it again, on a fresh install, and see if you can replicate the failure? And if you can, then do it again, but before running the playbook, check the output of the command `$ sudo iptables -L` in the terminal and see if there are any rules affecting SSH.

I'm going to close since I can't replicate on any of my test environments.

**Comment by Teglgaard** [comment]
I found the issue I believe. The issue is when the firewall is not setup to accept all as it normally is in the beginning. So the issue stops when the firewall is reset to the default.
