### ISSUE TITLE
Locks me out of server

### ISSUE THREAD

**Issue by ghost** [geerlingguy/ansible-role-firewall#53]
When using this role, I get to `TASK [geerlingguy.firewall : Copy firewall script into place.]` and I have been locked out of the server on port 22 which ansible is using to run tasks.

It seems that `TASK [geerlingguy.firewall : Flush iptables the first time playbook runs.]` is locking the server down to no open ports.

**Comment by ghost** [comment]
I reads this comment on digitalocean, and I wonder if it would be better with this functionality?

https://www.digitalocean.com/community/questions/help-with-iptables-causing-disconnection-and-blocking?answer=25822

**Comment by designermonkey** [comment]
FYI, this was me from another account.

**Comment by jduarter** [comment]
This is probably because the default policy of any of the chains was likely set to DROP/REJECT before the first execution of the role (probably you had some active rules before). I wrote a patch to fix it, pull request:  #61 

A solution before this pull request is merged is to manually perform this commands on the host before running the playbook by first time:
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -F

**Comment by leonsp** [comment]
I have the same issue.

Another solution to avoid lockout would be something like this:
```
iptables -F && iptables -I INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
```

Can #61 or something similar be merged?

**Comment by lenguyenthanh** [comment]
I'm also facing this problem. Please resolve this thanks!

**Comment by eugeneoden** [comment]
Ran into the same issue.  PR #61 resolves
